//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanProcessingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthManager
    {
        public int AuthManagerId { get; set; }
        public string AuthManagerName { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public Nullable<decimal> PhoneNo { get; set; }
    }
}
