//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanProcessingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectorDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InspectorDetail()
        {
            this.LoanForms = new HashSet<LoanForm>();
        }
    
        public int InspectorId { get; set; }
        public string InspectorName { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public Nullable<decimal> PhoneNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanForm> LoanForms { get; set; }
    }
}
